# Generated by Django 2.2.26 on 2022-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220822_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='month',
            field=models.DateField(),
        ),
    ]
