# Generated by Django 2.2.26 on 2022-09-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220906_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtokens',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oauthtokens',
            name='token',
            field=models.TextField(),
        ),
    ]
