# Generated by Django 2.2.26 on 2022-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220906_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='name',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='family_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiuser',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
