# Generated by Django 2.2.26 on 2023-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220925_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='subscription_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='source',
            field=models.CharField(choices=[('googleSheet', 'googleSheet'), ('googleDrive', 'googleDrive'), ('file', 'file')], default='active', max_length=100),
        ),
    ]
