# Generated by Django 2.2.26 on 2023-03-28 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230328_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='total_requests',
            field=models.IntegerField(default=0),
        ),
    ]
