# Generated by Django 2.2.26 on 2023-03-28 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230328_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
