# Generated by Django 2.2.26 on 2023-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_apiuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='card_number',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='card_type',
            field=models.CharField(default='visa', max_length=200),
            preserve_default=False,
        ),
    ]
