# Generated by Django 2.2.26 on 2023-03-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230328_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='update_card_url',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
