# Generated by Django 2.2.26 on 2023-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subscriptions_update_card_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='card_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='update_card_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
