# Generated by Django 2.2.26 on 2023-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230328_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='update_card_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
